vortoj.sample_language = {
	-- bones
	{"bones:bones",					"Huesos"},
	
	-- bucket
	{"bucket:bucket_empty",				"Cubo Vacio"},
	{"bucket:bucket_water",				"Cubo con Agua"},
	{"bucket:bucket_lava",				"Cubo con Lava"},
	
	-- default
	-- craftitems
	{"default:stick",					"Palito"},
	{"default:paper",					"Papel"},
	{"default:book",					"Libro"},
	{"default:coal_lump",				"Pepita de Carbon"},
	{"default:iron_lump",				"Pepita de Hierro"},
	{"default:copper_lump",				"Pepita de Cobre"},
	{"default:mese_crystal",				"Cristal de MESE"},
	{"default:gold_lump",				"Pepita de Oro"},
	{"default:diamond",					"Diamante"},
	{"default:clay_lump",				"Pepita de Arcilla"},
	{"default:steel_ingot",				"Lingote de Acero"},
	{"default:copper_ingot",				"Lingote de Cobre"},
	{"default:bronze_ingot",				"Lingote de Bronce"},
	{"default:gold_ingot",				"Lingote de Oro"},
	{"default:mese_crystal_fragment",		"Fragmento de Cristal de MESE"},
	{"default:clay_brick",				"Ladrillo de Arcilla"},
	{"default:scorched_stuff",			"Cosas Quemadas"},
	{"default:obsidian_shard",			"Fragmento de Obsidiana"},
	-- nodes
	{"default:stone",					"Piedra"},
	{"default:desert_stone",				"Piedra Desertica"},
	{"default:stone_with_coal",			"Piedra con Carbon"},
	{"default:stone_with_iron",			"Piedra con Hierro"},
	{"default:stone_with_copper",			"Piedra con Cobre"},
	{"default:stone_with_mese",			"Piedra con MESE"},
	{"default:stone_with_gold",			"Piedra con Oro"},
	{"default:stone_with_diamond",		"Piedra con Diamante"},
	{"default:stone_stonebrick",			"Bloque de Piedra"},
	{"default:stone_desert_stonebrick",	"Bloque de Piedra Desertica"},
	{"default:dirt_with_grass",			"Tierra con Hierba"},
	{"default:dirt_with_grass_footsteps",	"Tierra con Hierba y Pisadas"},
	{"default:dirt_with_snow",			"Tierra con Hierba y Nieve"},
	{"default:dirt",					"Tierra"},
	{"default:sand",					"Arena"},
	{"default:desert_sand",				"Arena Desertica"},
	{"default:gravel",					"Gravilla"},
	{"default:sandstone",				"Arenisca"},
	{"default:sandstonebrick",			"Ladrillo de Arenisca"},
	{"default:clay",					"Arcilla"},
	{"default:brick",					"Ladrillo"},
	{"default:tree",					"Arbol"},
	{"default:jungletree",				"Arbol Selvatico"},
	{"default:junglewood",				"Madera Selvatica"},
	{"default:jungleleaves",				"Hojas de Arbol Selvatico"},
	{"default:junglesapling",			"Brote de Arbol Selvatico"},
	{"default:junglegrass",				"Arbusto Selvatico"},
	{"default:leaves",					"Hojas"},
	{"default:cactus",					"Cacto"},
	{"default:papyrus",					"Papiro"},
	{"default:bookshelf",				"Libreria"},
	{"default:glass",					"Cristal"},
	{"default:fence_wood",				"Valla de Madera"},
	{"default:rail",					"Riel"},
	{"default:ladder",					"Escalerilla"},
	{"default:wood",					"Madera"},
	{"default:cloud",					"Nube"},
	{"default:water_flowing",			"Agua Fluyente"},
	{"default:water_source",				"Fuente de Agua"},
	{"default:lava_flowing",				"Lava Fluyente"},
	{"default:lava_source",				"Fuente de Lava"},
	{"default:torch",					"Antorcha"},
	{"default:sign_wall",				"Letrero"},
	{"default:chest",					"Cofre"},
	{"default:chest_locked",				"Cofre Cerrado"},
	{"default:furnace",					"Horno"},
	{"default:furnace_active",			"Horno Activo"},
	{"default:cobble",					"Adoquines"},
	{"default:mossycobble",				"Adoquines Enmohecidos"},
	{"default:coalblock",				"Bloque de Carbon"},
	{"default:steelblock",				"Bloque de Acero"},
	{"default:copperblock",				"Bloque de Cobre"},
	{"default:bronzeblock",				"Bloque de Bronce"},
	{"default:mese",					"Bloque de MESE"},
	{"default:goldblock",				"Bloque de Oro"},
	{"default:diamondblock",				"Bloque de Diamante"},
	{"default:obsidian_glass",			"Cristal de Obsidiana"},
	{"default:obsidian",				"Obsidiana"},
	{"default:nyancat",					"Gato Nyan"},
	{"default:nyancat_rainbow",			"Arcoiris de Gato Nyan"},
	{"default:sapling",					"Brote"},
	{"default:apple",					"Manzana"},
	{"default:dry_shrub",				"Arbusto Seco"},
	{"default:grass_1",					"Pasto"},
	{"default:grass_2",					"Pasto"},
	{"default:grass_3",					"Pasto"},
	{"default:grass_4",					"Pasto"},
	{"default:grass_5",					"Pasto"},
	{"default:ice",					"Hielo"},
	{"default:snow",					"Nieve"},
	{"default:snowblock",				"Bloque de Nieve"},
	-- tools
	{"default:pick_wood",				"Piqueta de Madera"},
	{"default:pick_stone",				"Piqueta de Piedra"},
	{"default:pick_copper",				"Piqueta de Cobre"},
	{"default:pick_steel",				"Piqueta de Acero"},
	{"default:pick_mese",				"Piqueta de MESE"},
	{"default:shovel_wood",				"Pala de Madera"},
	{"default:shovel_stone",				"Pala de Piedra"},
	{"default:shovel_copper",			"Pala de Cobre"},
	{"default:shovel_steel",				"Pala de Acero"},
	{"default:axe_wood",				"Hacha de Madera"},
	{"default:axe_stone",				"Hacha de Piedra"},
	{"default:axe_copper",				"Hacha de Cobre"},
	{"default:axe_steel",				"Hacha de Acero"},
	{"default:sword_wood",				"Espada de Madera"},
	{"default:sword_stone",				"Espada de Piedra"},
	{"default:sword_copper",				"Espada de Cobre"},
	{"default:sword_steel",				"Espada de Acero"},
	
	-- doors
	{"doors:door_wood",					"Puerta de Madera"},
	{"doors:door_steel",				"Puerta de Acero"},
	
	-- dye
	{"dye:white",						"Tinte Blanco"},
	{"dye:grey",						"Tinte Gris"},
	{"dye:dark_grey",					"Tinte Gris Oscuro"},
	{"dye:black",						"Tinte Negro"},
	{"dye:violet",						"Tinte Violeta"},
	{"dye:blue",						"Tinte Azul"},
	{"dye:cyan",						"Tinte Turquesa"},
	{"dye:dark_green",					"Tinte Verde Oscuro"},
	{"dye:green",						"Tinte Verde"},
	{"dye:yellow",						"Tinte Amarillo"},
	{"dye:brown",						"Tinte Marron"},
	{"dye:orange",						"Tinte Naranja"},
	{"dye:red",						"Tinte Rojo"},
	{"dye:magenta",					"Tinte Magenta"},
	{"dye:pink",						"Tinte Rosa"},
	
	-- farming
	{"farming:soil",					"Tierra"},
	{"farming:soil_wet",				"Tierra Mojada"},
	{"farming:seed_cotton",				"Semilla de Algodon"},
	{"farming:cotton",					"Algodon"},
	{"farming:cotton_1",				"Algodon"},
	{"farming:cotton_2",				"Algodon"},
	{"farming:cotton_3",				"Algodon"},
	{"farming:cotton_4",				"Algodon"},
	{"farming:cotton_5",				"Algodon"},
	{"farming:sting",					"Cuerda"},
	{"farming:hoe_wood",				"Azadon de Madera"},
	{"farming:hoe_stone",				"Azadon de Piedra"},
	{"farming:hoe_steel",				"Azadon de Acero"},
	{"farming:hoe_bronze",				"Azadon de Bronce"},
	{"farming:hoe_mese",				"Azadon de MESE"},
	{"farming:weed",					"Hierba"},
	{"farming:seed_wheat",				"Semilla de Trigo"},
	{"farming:wheat",					"Trigo"},
	{"farming:wheat_1",					"Trigo"},
	{"farming:wheat_2",					"Trigo"},
	{"farming:wheat_3",					"Trigo"},
	{"farming:wheat_4",					"Trigo"},
	{"farming:wheat_5",					"Trigo"},
	{"farming:wheat_6",					"Trigo"},
	{"farming:wheat_7",					"Trigo"},
	{"farming:wheat_8",					"Trigo"},
	{"farming:flour",					"Harina"},
	{"farming:dough",					"Masa"},
	{"farming:bread",					"Pan"},
	
	-- fire
	{"fire:basic_flame",				"Fuego"},
	
	-- flowers
	{"flowers:dandelion_white",			"Diente de Leon Blanco"},
	{"flowers:dandelion_yellow",			"Diente de Leon Amarillo"},
	{"flowers:geranium",				"Geranio"},
	{"flowers:rose",					"Rosa"},
	{"flowers:tulip",					"Tulipan"},
	{"flowers:viola",					"Violeta"},
	
	-- nodetest
	{"nodetest:bone",					"Hueso"},
	{"nodetest:desert_sandstone",			"Arenisca Desertica"},
	{"nodetest:rock",					"Roca"},
	{"nodetest:tree_horizontal",			"Arbol (Horizontal)"},
	{"nodetest:jungletree_horizontal",		"Arbol Selvatico (Horizontal)"},
	{"nodetest:papyrus_roots",			"Raices de Papiro"},
	{"nodetest:conifersapling",			""},
	{"nodetest:conifertree",				""},
	{"nodetest:coniferleaves_1",			""},
	{"nodetest:coniferleaves_2",			""},
	{"nodetest:conifertree_horizontal",	""},
	{"nodetest:spearwood",				""},
	{"nodetest:spearstone",				""},
	
	-- pots
	{"pots:pot",						""},
	{"pots:cactus",					""},
	{"pots:dandelion_white",				""},
	{"pots:dandelion_yellow",			""},
	{"pots:geranium",					""},
	{"pots:rose",						""},
	{"pots:tulip",						""},
	{"pots:viola",						""},
	{"pots:viola",						""},
	
	-- screwdriver
	{"screwdriver:screwdriver",			""},
	{"screwdriver:screwdriver1",			""},
	{"screwdriver:screwdriver2",			""},
	{"screwdriver:screwdriver3",			""},
	{"screwdriver:screwdriver4",			""},
	
	-- wool
	{"wool:white",						""},
	{"wool:grey",						""},
	{"wool:dark_grey",					""},
	{"wool:black",						""},
	{"wool:violet",					""},
	{"wool:blue",						""},
	{"wool:cyan",						""},
	{"wool:dark_green",					""},
	{"wool:green",						""},
	{"wool:yellow",					""},
	{"wool:brown",						""},
	{"wool:orange",					""},
	{"wool:red",						""},
	{"wool:magenta",					""},
	{"wool:pink",						""},

	-- vessels
	{"vessels:glass_bottle",				""},
	{"vessels:drinking_glass",			""},
	{"vessels:steel_bottle",				""},
	{"vessels:glass_fragments",			""},
}
